### ISSUE TITLE
Компонент Select

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/2020-ux-booking#2]
![изображение](https://user-images.githubusercontent.com/6851647/112166739-5692fd00-8c09-11eb-9dc3-100eb10474df.png)
![изображение](https://user-images.githubusercontent.com/6851647/112166759-5c88de00-8c09-11eb-83f9-03ec05d7ac7d.png)

**Comment by NataliaKly** [comment]
![1](https://user-images.githubusercontent.com/36840773/112337574-785ab580-8cd7-11eb-991a-36e8f2090bd7.png)
